export const VIDEO_TYPES = {
  CLIP: 'Clip',
  DOCUMENTARY: 'Documentary',
  SERMON: 'Sermon',
};

export const VIDEOS = {
  '58cff3cc-9841-44fc-b267-08a0cd0ab4e4': {
    title: 'Once Saved Always Saved',
    type: VIDEO_TYPES.SERMON,
    description: 'This sermon goes over the doctrine of eternal security and explains from the Bible how you can never lose your salvation.',
    thumbnail: '',
    src: 'https://www.kjv1611only.com/video/02preaching/Sermons_Pastor_Anderson/Once_Saved_Always_Saved.mp4',
  },
  '62887161-e25d-4ce3-b822-c81b600c84ff': {
    title: 'Repent of Your Sins for Salvation is a False Doctrine',
    type: VIDEO_TYPES.CLIP,
    description: 'This clip shows why repenting of your sins or turning from your sins in relation to salvation is a false doctrine and a false gospel.',
    thumbnail: '',
    src: 'https://www.kjv1611only.com/video/02preaching/Sermon_Clips_Pastor_Pozarnsky/Repent_Of_Your_Sins_For_Salvation_Is_A_False_Doctrine.mp4',
  },
  '562b0ec0-af3b-46df-9272-8811bb27e751': {
    title: 'The Preserved Bible',
    type: VIDEO_TYPES.DOCUMENTARY,
    description: 'The Preserved Bible is a documentary explaining the doctrine of preservation and why the Bible has been preserved. Additionally, the film explains through history, scripture, and interviews why the King James Bible is the preserved Bible in English today.',
    thumbnail: '/images/documentaries/preserved_bible.jpeg',
    src: 'https://www.kjv1611only.com/video/06docs/docs/The_Preserved_Bible.mp4',
  },
  '8ea2683e-70e9-4396-b073-db29f07afaae': {
    title: 'Being Baptist',
    type: VIDEO_TYPES.DOCUMENTARY,
    description: 'Being Baptist traces the history from the historic anabaptists to the impact of the independent fundamental churches of today.',
    thumbnail: '/images/documentaries/being_baptist.png',
    src: 'https://www.kjv1611only.com/video/06docs/docs/Being_Baptist.mp4',
  },
}

export const LANGUAGE_NAMES = {
  'en': 'English',
  'af-ZA': 'Afrikaans',
  'am-ET': 'አማርኛ ኢትዮጵያዊ',
  'ar-SA': 'عربي',
  'bg-BG': 'български',
  'bn-BD': 'বাংলা',
  'de-DE': 'Deutsch',
  'bs-BA': 'босански',
  'el-GR': 'Ελληνικά',
  'eo': 'Esperanto',
  'es-MX': 'Español (Castilian)',
  'fa-IR': 'فارسی',
  'fr-FR': 'Français',
  'gu-IN': 'ગુજરાતી',
  'hi-IN': 'हिंदी',
  'hr-HR': 'Hrvatski',
  'ht': 'Creole (Kreyòl)',
  'hu-HU': 'Magyar Nyelv',
  'ig-NG': 'Ásụ̀sụ́ Ìgbò',
  'ja-JP': '日本語',
  'kn-IN': 'ಕನ್ನಡ',
  'ko-KR': '한국어',
  'ml-IN': 'മലയാളം',
  'mr-IN': 'मराठी',
  'ne-NP': 'नेपाली',
  'nl-NL': 'Nederlands',
  'no-NO': 'Norsk',
  'or-IN': 'ଓଡ଼ିଆ',
  'pa-IN': 'پنجابی (ਪੰਜਾਬੀ)',
  'pl-PL': 'Polski',
  'pt-BR': 'Português',
  'ro-RO': 'Română',
  'ru-RU': 'Pусский',
  'sk-SK': 'Slovenčina',
  'sr-RS': 'Cрпски',
  'sv-SE': 'Svenska',
  'sw-KE': 'كِيْسْوَاحِيْلِيْ (Kiswahili)',
  'ta-IN': 'தமிழ்',
  'te-IN': 'తెలుగు',
  'th-TH': 'ภาษาไทย',
  'tl-PH': 'Filipino (Tagalog)',
  'uk-UA': 'Yкраїнська',
  'vi-VN': 'Tiếng Việt',
  'yo-NG': 'Èdè Yorùbá (عِدعِ يوْرُب)',
  'zh-CN': '官话',
  'zh-HANT': '廣東話',
}
