import { VIDEO_TYPES } from "@/lib/constants";
import { deepSpread } from "@/lib/helpers";

const defaultConfig = {
  name: 'Bible Way to Heaven',
  showName: true,
  logo: {
    url: '/images/bw2h_logo_simple.png',
    height: 42,
    width: 42,
  },
  languages: {
    disable: [],
    feature: [],
  },
  recommendedVideos: [
    '58cff3cc-9841-44fc-b267-08a0cd0ab4e4',
    '562b0ec0-af3b-46df-9272-8811bb27e751',
  ],
  videos: {
    'en': 'https://www.kjv1611only.com/video/01salvation/Pastor_Anderson.mp4',
    'af-ZA': 'https://www.kjv1611only.com/video/01salvation/Afrikaans.mp4',
    'am-ET': 'https://www.kjv1611only.com/video/01salvation/Amharic_Ethiopean.mp4',
    'ar-SA': 'https://www.kjv1611only.com/video/01salvation/Arabic.mp4',
    'bg-BG': 'https://www.kjv1611only.com/video/01salvation/Bulgarian.mp4',
    'bn-BD': 'https://www.kjv1611only.com/video/01salvation/Bengali.mp4',
    'bs-BA': 'https://www.kjv1611only.com/video/01salvation/Bosnian.mp4',
    'de-DE': 'https://www.kjv1611only.com/video/01salvation/German.mp4',
    'el-GR': 'https://www.kjv1611only.com/video/01salvation/Greek.mp4',
    'eo': 'https://www.kjv1611only.com/video/01salvation/Esperanto.mp4',
    'es-MX': 'https://www.kjv1611only.com/video/01salvation/Spanish_2.mp4',
    'fa-IR': 'https://www.kjv1611only.com/video/01salvation/Farsi.mp4',
    'fr-FR': 'https://www.kjv1611only.com/video/01salvation/French_1.mp4',
    'gu-IN': 'https://www.kjv1611only.com/video/01salvation/Gujarati.mp4',
    'hi-IN': 'https://www.kjv1611only.com/video/01salvation/Hindi.mp4',
    'hr-HR': 'https://www.kjv1611only.com/video/01salvation/Croatian.mp4',
    'ht': 'https://www.kjv1611only.com/video/01salvation/Hatian_Creole.mp4',
    'hu-HU': 'https://www.kjv1611only.com/video/01salvation/Hungarian.mp4',
    'ig-NG': 'https://www.kjv1611only.com/video/01salvation/Igbo.mp4',
    'ja-JP': 'https://www.kjv1611only.com/video/01salvation/Japanese.mp4',
    'kn-IN': 'https://www.kjv1611only.com/video/01salvation/Kannada.mp4',
    'ko-KR': 'https://www.kjv1611only.com/video/01salvation/Korean.mp4',
    'ml-IN': 'https://www.kjv1611only.com/video/01salvation/Malayalam.mp4',
    'mr-IN': 'https://www.kjv1611only.com/video/01salvation/Marathi.mp4',
    'ne-NP': 'https://www.kjv1611only.com/video/01salvation/Nepali.mp4',
    'nl-NL': 'https://www.kjv1611only.com/video/01salvation/Dutch.mp4',
    'no-NO': 'https://www.kjv1611only.com/video/01salvation/Norwegian.mp4',
    'or-IN': 'https://www.kjv1611only.com/video/01salvation/Oriya.mp4',
    'pa-IN': 'https://www.kjv1611only.com/video/01salvation/Punjabi.mp4',
    'pl-PL': 'https://www.kjv1611only.com/video/01salvation/Polish.mp4',
    'pt-BR': 'https://www.kjv1611only.com/video/01salvation/Portuguese_2.mp4',
    'ro-RO': 'https://www.kjv1611only.com/video/01salvation/Romanian.mp4',
    'ru-RU': 'https://www.kjv1611only.com/video/01salvation/Russian.mp4',
    'sk-SK': 'https://www.kjv1611only.com/video/01salvation/Slovak.mp4',
    'sr-RS': 'https://www.kjv1611only.com/video/01salvation/Serbian.mp4',
    'sv-SE': 'https://www.kjv1611only.com/video/01salvation/Swedish.mp4',
    'sw-KE': 'https://www.kjv1611only.com/video/01salvation/Swahili.mp4',
    'ta-IN': 'https://www.kjv1611only.com/video/01salvation/Tamil.mp4',
    'te-IN': 'https://www.kjv1611only.com/video/01salvation/Telugu.mp4',
    'th-TH': 'https://www.kjv1611only.com/video/01salvation/Thai.mp4',
    'tl-PH': 'https://www.kjv1611only.com/video/01salvation/Tagalog.mp4',
    'uk-UA': 'https://www.kjv1611only.com/video/01salvation/Ukrainian.mp4',
    'vi-VN': 'https://www.kjv1611only.com/video/01salvation/Vietnamese.mp4',
    'yo-NG': 'https://www.kjv1611only.com/video/01salvation/Yoruba.mp4',
    'zh-CN': 'https://www.kjv1611only.com/video/01salvation/Mandarin.mp4',
    'zh-HANT': 'https://www.kjv1611only.com/video/01salvation/Cantonese.mp4',
  },
};

export function defineConfig(config) {
  return deepSpread(defaultConfig, config);
}
